In [1]:
import numpy as np

In [3]:
a = np.array([[1, 6], 
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [10]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [18]:
a_centered_sp = (a_centered[0, 0] * a_centered[0, 1] + a_centered[1, 0] * a_centered[1, 1] + a_centered[2, 0] * a_centered[2, 1] + \
                a_centered[3, 0] * a_centered[3, 1] + a_centered[4, 0] * a_centered[4, 1]) / 4
a_centered_sp

2.0

In [19]:
np.cov(a.T)[0, 1]

2.0